ALTER TABLE languages
    ALTER COLUMN index DROP NOT NULL,
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE abilities
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE classes
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN hit_dice SET NOT NULL;

ALTER TABLE subraces
    ALTER COLUMN race_id SET NOT NULL,
    ALTER COLUMN name SET NOT NULL;
